-- Hyprland Lua config (Hyprland >= 0.55).
-- See https://wiki.hypr.land/Configuring/Start/
-- Replaces the old autogenerated hyprland.conf stub.

---------------------
---- MY PROGRAMS ----
---------------------

local terminal = "alacritty"
local browser  = "firefox"

------------------
---- MONITORS ----
------------------

hl.monitor({
	output   = "",
	mode     = "preferred",
	position = "auto",
	scale    = "auto",
})

-------------
---- ENV ----
-------------

-- Cursor: Bibata Modern Classic for both Xcursor and Hyprland's hyprcursor.
hl.env("XCURSOR_THEME",    "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE",     "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE",  "24")

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
	hl.exec_cmd("mako")
	hl.exec_cmd("waybar")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("$HOME/.config/awww/wallpaper.sh")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("blueman-applet")
end)

----------------------
---- KEYBINDINGS ----
----------------------

local mainMod = "SUPER"

-- General commands
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))

-- Quick launches
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("alacritty -e yazi"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("wofi --show drun"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("$HOME/.config/awww/wallpaper.sh"))
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("wlogout"))

-- Screenshots
local shot = "$HOME/.config/screenshot/screenshot.sh"
hl.bind("Print",            hl.dsp.exec_cmd(shot .. " region-copy"))
hl.bind("SHIFT + Print",    hl.dsp.exec_cmd(shot .. " region-edit"))
hl.bind(mainMod .. " + Print",  hl.dsp.exec_cmd(shot .. " window"))
hl.bind("CTRL + Print",     hl.dsp.exec_cmd(shot .. " full"))

-- Screen focus
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- Workspace management
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Cycle workspaces
hl.bind(mainMod .. " + bracketleft", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + bracketright", hl.dsp.focus({ workspace = "e+1" }))

-- Mouse controls
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
	input = {
		-- Use Caps Lock as the XKB Compose key.
		-- e.g. Caps + o + o -> "°", Caps + - + - + - -> "—", Caps + ' + e -> "é"
		kb_options = "compose:caps",
	},

	general = {
		gaps_in          = 5,
		gaps_out         = 20,

		border_size      = 2,

		col              = {
			-- Tokyo Night: blue -> purple gradient active, muted highlight inactive
			active_border   = { colors = { "rgba(7aa2f7ee)", "rgba(bb9af7ee)" }, angle = 45 },
			inactive_border = "rgba(292e42aa)",
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing    = false,

		layout           = "dwindle",
	},

	decoration = {
		rounding         = 10,
		rounding_power   = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity   = 1.0,
		inactive_opacity = 1.0,

		shadow           = {
			enabled      = true,
			range        = 4,
			render_power = 3,
			color        = 0xee16161e,
		},

		blur             = {
			enabled  = true,
			size     = 3,
			passes   = 1,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = true,
	},
})

-----------------
---- RULES ----
-----------------

-- Frosted-glass Waybar (pairs with the slightly transparent bar background)
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })

-- Steam dialogs (Friends List, Sign in, Settings, Steam Guard, news popups…)
-- float and center. The main library window (title "Steam") is forced back to
-- tiled by the third rule — Hyprland's regex engine has flaky lookahead
-- support, so this two-rule pattern is more reliable than negative matching.
hl.window_rule({ match = { class = "^(steam)$" }, float = true })
hl.window_rule({ match = { class = "^(steam)$" }, center = true })
hl.window_rule({ match = { class = "^(steam)$", title = "^Steam$" }, tile = true })

-- satty (screenshot annotator) — should always float and center.
hl.window_rule({ match = { class = "^(com\\.gabm\\.satty)$" }, float = true })
hl.window_rule({ match = { class = "^(com\\.gabm\\.satty)$" }, center = true })

-- blueman-manager (Bluetooth Devices) — float and center.
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, center = true })
